### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by paperc07** [automate0/the-tower#1]
@bjyxm Saw this and was wondering does it work for the game on app store?

**Comment by paperc07** [comment]
If so this is the error im getting when trying to run the python run_state_check.py

Traceback (most recent call last):
  File "C:\Users\paper\Desktop\the-tower-master\run_state_check.py", line 9, in <module>
    cap = device.capture()
          ^^^^^^^^^^^^^^^^
  File "C:\Users\paper\Desktop\the-tower-master\android_device.py", line 16, in capture
    screen = self.device.screencap()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paper\AppData\Local\Programs\Python\Python311\Lib\site-packages\ppadb\command\transport\__init__.py", line 45, in screencap
    conn.send(cmd)
  File "C:\Users\paper\AppData\Local\Programs\Python\Python311\Lib\site-packages\ppadb\connection.py", line 84, in send
    return self._check_status()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paper\AppData\Local\Programs\Python\Python311\Lib\site-packages\ppadb\connection.py", line 90, in _check_status
    raise RuntimeError("ERROR: {} {}".format(repr(recv), error))
RuntimeError: ERROR: 'FAIL' 0006

**Comment by paperc07** [comment]
Fixed this problem now its just saying APP IS NOT RUNNING OVER AND OVER AGAIN. It's in potrait 720X1280


![image](https://github.com/bjyxm/the-tower/assets/9095222/27ed1aae-4ebd-4359-9b59-f60ac6f39a3f)

**Comment by fgdaniel** [comment]
> If so this is the error im getting when trying to run the python run_state_check.py
> 
> Traceback (most recent call last): File "C:\Users\paper\Desktop\the-tower-master\run_state_check.py", line 9, in cap = device.capture() ^^^^^^^^^^^^^^^^ File "C:\Users\paper\Desktop\the-tower-master\android_device.py", line 16, in capture screen = self.device.screencap() ^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\paper\AppData\Local\Programs\Python\Python311\Lib\site-packages\ppadb\command\transport__init__.py", line 45, in screencap conn.send(cmd) File "C:\Users\paper\AppData\Local\Programs\Python\Python311\Lib\site-packages\ppadb\connection.py", line 84, in send return self._check_status() ^^^^^^^^^^^^^^^^^^^^ File "C:\Users\paper\AppData\Local\Programs\Python\Python311\Lib\site-packages\ppadb\connection.py", line 90, in _check_status raise RuntimeError("ERROR: {} {}".format(repr(recv), error)) RuntimeError: ERROR: 'FAIL' 0006

How to you resolve this error because i have same error

**Comment by paperc07** [comment]
I don't believe so. I quit playing shortly after also.
